import { foldText } from "./normalize.ts";
import { AMBIGUOUS_PLACES, CITY_TO_COUNTRY, SUBDIVISION_NAMES } from "./places.ts";
import type { CountryIndex } from "./types.ts";

export const COUNTRY_NAMES: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin (French part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé and Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten (Dutch part)",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  XK: "Kosovo",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const COUNTRY_ISO3: Record<string, string> = {
  and: "AD",
  are: "AE",
  afg: "AF",
  atg: "AG",
  aia: "AI",
  alb: "AL",
  arm: "AM",
  ago: "AO",
  ata: "AQ",
  arg: "AR",
  asm: "AS",
  aut: "AT",
  aus: "AU",
  abw: "AW",
  ala: "AX",
  aze: "AZ",
  bih: "BA",
  brb: "BB",
  bgd: "BD",
  bel: "BE",
  bfa: "BF",
  bgr: "BG",
  bhr: "BH",
  bdi: "BI",
  ben: "BJ",
  blm: "BL",
  bmu: "BM",
  brn: "BN",
  bol: "BO",
  bes: "BQ",
  bra: "BR",
  bhs: "BS",
  btn: "BT",
  bvt: "BV",
  bwa: "BW",
  blr: "BY",
  blz: "BZ",
  can: "CA",
  cck: "CC",
  cod: "CD",
  caf: "CF",
  cog: "CG",
  che: "CH",
  civ: "CI",
  cok: "CK",
  chl: "CL",
  cmr: "CM",
  chn: "CN",
  col: "CO",
  cri: "CR",
  cub: "CU",
  cpv: "CV",
  cuw: "CW",
  cxr: "CX",
  cyp: "CY",
  cze: "CZ",
  deu: "DE",
  dji: "DJ",
  dnk: "DK",
  dma: "DM",
  dom: "DO",
  dza: "DZ",
  ecu: "EC",
  est: "EE",
  egy: "EG",
  esh: "EH",
  eri: "ER",
  esp: "ES",
  eth: "ET",
  fin: "FI",
  fji: "FJ",
  flk: "FK",
  fsm: "FM",
  fro: "FO",
  fra: "FR",
  gab: "GA",
  gbr: "GB",
  grd: "GD",
  geo: "GE",
  guf: "GF",
  ggy: "GG",
  gha: "GH",
  gib: "GI",
  grl: "GL",
  gmb: "GM",
  gin: "GN",
  glp: "GP",
  gnq: "GQ",
  grc: "GR",
  sgs: "GS",
  gtm: "GT",
  gum: "GU",
  gnb: "GW",
  guy: "GY",
  hkg: "HK",
  hmd: "HM",
  hnd: "HN",
  hrv: "HR",
  hti: "HT",
  hun: "HU",
  idn: "ID",
  irl: "IE",
  isr: "IL",
  imn: "IM",
  ind: "IN",
  iot: "IO",
  irq: "IQ",
  irn: "IR",
  isl: "IS",
  ita: "IT",
  jey: "JE",
  jam: "JM",
  jor: "JO",
  jpn: "JP",
  ken: "KE",
  kgz: "KG",
  khm: "KH",
  kir: "KI",
  com: "KM",
  kna: "KN",
  prk: "KP",
  kor: "KR",
  kwt: "KW",
  cym: "KY",
  kaz: "KZ",
  lao: "LA",
  lbn: "LB",
  lca: "LC",
  lie: "LI",
  lka: "LK",
  lbr: "LR",
  lso: "LS",
  ltu: "LT",
  lux: "LU",
  lva: "LV",
  lby: "LY",
  mar: "MA",
  mco: "MC",
  mda: "MD",
  mne: "ME",
  maf: "MF",
  mdg: "MG",
  mhl: "MH",
  mkd: "MK",
  mli: "ML",
  mmr: "MM",
  mng: "MN",
  mac: "MO",
  mnp: "MP",
  mtq: "MQ",
  mrt: "MR",
  msr: "MS",
  mlt: "MT",
  mus: "MU",
  mdv: "MV",
  mwi: "MW",
  mex: "MX",
  mys: "MY",
  moz: "MZ",
  nam: "NA",
  ncl: "NC",
  ner: "NE",
  nfk: "NF",
  nga: "NG",
  nic: "NI",
  nld: "NL",
  nor: "NO",
  npl: "NP",
  nru: "NR",
  niu: "NU",
  nzl: "NZ",
  omn: "OM",
  pan: "PA",
  per: "PE",
  pyf: "PF",
  png: "PG",
  phl: "PH",
  pak: "PK",
  pol: "PL",
  spm: "PM",
  pcn: "PN",
  pri: "PR",
  pse: "PS",
  prt: "PT",
  plw: "PW",
  pry: "PY",
  qat: "QA",
  reu: "RE",
  rou: "RO",
  srb: "RS",
  rus: "RU",
  rwa: "RW",
  sau: "SA",
  slb: "SB",
  syc: "SC",
  sdn: "SD",
  swe: "SE",
  sgp: "SG",
  shn: "SH",
  svn: "SI",
  sjm: "SJ",
  svk: "SK",
  sle: "SL",
  smr: "SM",
  sen: "SN",
  som: "SO",
  sur: "SR",
  ssd: "SS",
  stp: "ST",
  slv: "SV",
  sxm: "SX",
  syr: "SY",
  swz: "SZ",
  tca: "TC",
  tcd: "TD",
  atf: "TF",
  tgo: "TG",
  tha: "TH",
  tjk: "TJ",
  tkl: "TK",
  tls: "TL",
  tkm: "TM",
  tun: "TN",
  ton: "TO",
  tur: "TR",
  tto: "TT",
  tuv: "TV",
  twn: "TW",
  tza: "TZ",
  ukr: "UA",
  uga: "UG",
  umi: "UM",
  usa: "US",
  ury: "UY",
  uzb: "UZ",
  vat: "VA",
  vct: "VC",
  ven: "VE",
  vgb: "VG",
  vir: "VI",
  vnm: "VN",
  vut: "VU",
  wlf: "WF",
  wsm: "WS",
  xkx: "XK",
  yem: "YE",
  myt: "YT",
  zaf: "ZA",
  zmb: "ZM",
  zwe: "ZW",
};

/**
 * Other names for a country -> ISO2: short forms and abbreviations, older names,
 * names in other major languages and native names in their own script. Keys are
 * written naturally; buildCountryIndex (and the popup search) fold them.
 */
export const COUNTRY_ALIASES: Record<string, string> = {
  // United States
  usa: "US",
  "u.s.a.": "US",
  america: "US",
  "united states of america": "US",
  "the states": "US",
  murica: "US",
  merica: "US",
  amerika: "US",
  "amerika serikat": "US",
  "estados unidos": "US",
  eeuu: "US",
  "ee.uu.": "US",
  eua: "US",
  "états-unis": "US",
  "vereinigte staaten": "US",
  "stati uniti": "US",
  abd: "US",
  // United Kingdom
  uk: "GB",
  "u.k.": "GB",
  britain: "GB",
  "great britain": "GB",
  england: "GB",
  "united kingdom of great britain and northern ireland": "GB",
  "reino unido": "GB",
  "royaume-uni": "GB",
  "vereinigtes königreich": "GB",
  "regno unito": "GB",
  inglaterra: "GB",
  angleterre: "GB",
  ingiltere: "GB",
  cymru: "GB",
  // Europe
  deutschland: "DE",
  alemania: "DE",
  allemagne: "DE",
  germania: "DE",
  alemanha: "DE",
  almanya: "DE",
  francia: "FR",
  frankreich: "FR",
  frança: "FR",
  fransa: "FR",
  españa: "ES",
  spanien: "ES",
  espagne: "ES",
  spagna: "ES",
  espanha: "ES",
  ispanya: "ES",
  italia: "IT",
  italien: "IT",
  italie: "IT",
  italya: "IT",
  holland: "NL",
  nederland: "NL",
  holanda: "NL",
  "países bajos": "NL",
  niederlande: "NL",
  "pays-bas": "NL",
  hollanda: "NL",
  "the netherlands": "NL",
  belgië: "BE",
  belgique: "BE",
  belgien: "BE",
  bélgica: "BE",
  schweiz: "CH",
  suisse: "CH",
  svizzera: "CH",
  suiza: "CH",
  helvetia: "CH",
  österreich: "AT",
  sverige: "SE",
  suecia: "SE",
  schweden: "SE",
  norge: "NO",
  noreg: "NO",
  noruega: "NO",
  norwegen: "NO",
  danmark: "DK",
  dinamarca: "DK",
  suomi: "FI",
  finnland: "FI",
  éire: "IE",
  irlanda: "IE",
  irland: "IE",
  ελλάδα: "GR",
  ελλάς: "GR",
  hellas: "GR",
  grecia: "GR",
  griechenland: "GR",
  yunanistan: "GR",
  κύπρος: "CY",
  kıbrıs: "CY",
  polska: "PL",
  polonia: "PL",
  polen: "PL",
  česko: "CZ",
  "česká republika": "CZ",
  "czech republic": "CZ",
  czechia: "CZ",
  tschechien: "CZ",
  slovensko: "SK",
  "slovak republic": "SK",
  magyarország: "HU",
  ungarn: "HU",
  rumania: "RO",
  rumänien: "RO",
  românia: "RO",
  българия: "BG",
  srbija: "RS",
  србија: "RS",
  hrvatska: "HR",
  slovenija: "SI",
  bosnia: "BA",
  herzegovina: "BA",
  "bosna i hercegovina": "BA",
  "crna gora": "ME",
  "црна гора": "ME",
  makedonija: "MK",
  "северна македонија": "MK",
  fyrom: "MK",
  shqipëria: "AL",
  shqipëri: "AL",
  kosova: "XK",
  україна: "UA",
  украина: "UA",
  ukraina: "UA",
  "the ukraine": "UA",
  russia: "RU",
  "russian federation": "RU",
  россия: "RU",
  rossiya: "RU",
  rusia: "RU",
  russland: "RU",
  russie: "RU",
  rusya: "RU",
  беларусь: "BY",
  byelorussia: "BY",
  lietuva: "LT",
  latvija: "LV",
  eesti: "EE",
  moldavia: "MD",
  vatican: "VA",
  "vatican city state": "VA",
  "holy see": "VA",
  // Türkiye, Caucasus, Central Asia
  türkiye: "TR",
  turkey: "TR",
  turquía: "TR",
  türkei: "TR",
  turquie: "TR",
  sakartvelo: "GE",
  საქართველო: "GE",
  hayastan: "AM",
  հայաստան: "AM",
  azərbaycan: "AZ",
  qazaqstan: "KZ",
  қазақстан: "KZ",
  казахстан: "KZ",
  oʻzbekiston: "UZ",
  ozbekiston: "UZ",
  ўзбекистон: "UZ",
  узбекистан: "UZ",
  кыргызстан: "KG",
  "kyrgyz republic": "KG",
  тоҷикистон: "TJ",
  монгол: "MN",
  "монгол улс": "MN",
  // East and Southeast Asia
  中国: "CN",
  中國: "CN",
  中华人民共和国: "CN",
  zhongguo: "CN",
  prc: "CN",
  "mainland china": "CN",
  "people's republic of china": "CN",
  chine: "CN",
  cina: "CN",
  台灣: "TW",
  台湾: "TW",
  臺灣: "TW",
  中華民國: "TW",
  "republic of china": "TW",
  formosa: "TW",
  香港: "HK",
  澳門: "MO",
  澳门: "MO",
  macau: "MO",
  日本: "JP",
  日本国: "JP",
  nippon: "JP",
  nihon: "JP",
  japón: "JP",
  giappone: "JP",
  japão: "JP",
  "south korea": "KR",
  "republic of korea": "KR",
  대한민국: "KR",
  한국: "KR",
  "corea del sur": "KR",
  "coreia do sul": "KR",
  südkorea: "KR",
  "north korea": "KP",
  dprk: "KP",
  조선: "KP",
  북한: "KP",
  ประเทศไทย: "TH",
  ไทย: "TH",
  tailandia: "TH",
  "viet nam": "VN",
  ລາວ: "LA",
  "lao pdr": "LA",
  កម្ពុជា: "KH",
  kampuchea: "KH",
  camboya: "KH",
  burma: "MM",
  မြန်မာ: "MM",
  新加坡: "SG",
  singapura: "SG",
  pilipinas: "PH",
  filipinas: "PH",
  pinas: "PH",
  phillipines: "PH",
  philipines: "PH",
  "east timor": "TL",
  // South Asia
  bharat: "IN",
  hindustan: "IN",
  भारत: "IN",
  ভারত: "IN",
  இந்தியா: "IN",
  inde: "IN",
  indien: "IN",
  hindistan: "IN",
  پاکستان: "PK",
  पाकिस्तान: "PK",
  বাংলাদেশ: "BD",
  नेपाल: "NP",
  "ශ්‍රී ලංකාව": "LK",
  இலங்கை: "LK",
  ceylon: "LK",
  افغانستان: "AF",
  // Middle East and North Africa
  ایران: "IR",
  persia: "IR",
  العراق: "IQ",
  سوريا: "SY",
  "syrian arab republic": "SY",
  لبنان: "LB",
  liban: "LB",
  الأردن: "JO",
  الاردن: "JO",
  فلسطين: "PS",
  "state of palestine": "PS",
  "palestinian territories": "PS",
  "west bank": "PS",
  "gaza strip": "PS",
  ישראל: "IL",
  مصر: "EG",
  misr: "EG",
  égypte: "EG",
  egipto: "EG",
  ägypten: "EG",
  ليبيا: "LY",
  تونس: "TN",
  tunisie: "TN",
  الجزائر: "DZ",
  algérie: "DZ",
  argelia: "DZ",
  المغرب: "MA",
  maroc: "MA",
  marruecos: "MA",
  marokko: "MA",
  السودان: "SD",
  اليمن: "YE",
  السعودية: "SA",
  "المملكة العربية السعودية": "SA",
  ksa: "SA",
  saudi: "SA",
  saudia: "SA",
  "kingdom of saudi arabia": "SA",
  "arabia saudita": "SA",
  الإمارات: "AE",
  "الإمارات العربية المتحدة": "AE",
  uae: "AE",
  "u.a.e.": "AE",
  emirates: "AE",
  قطر: "QA",
  الكويت: "KW",
  البحرين: "BH",
  "سلطنة عمان": "OM",
  "sultanate of oman": "OM",
  // Sub-Saharan Africa
  ኢትዮጵያ: "ET",
  soomaaliya: "SO",
  naija: "NG",
  "9ja": "NG",
  rsa: "ZA",
  mzansi: "ZA",
  "suid-afrika": "ZA",
  sudáfrica: "ZA",
  "dr congo": "CD",
  drc: "CD",
  rdc: "CD",
  "democratic republic of congo": "CD",
  "congo kinshasa": "CD",
  zaire: "CD",
  "congo brazzaville": "CG",
  "republic of congo": "CG",
  "ivory coast": "CI",
  cameroun: "CM",
  kamerun: "CM",
  "cape verde": "CV",
  swaziland: "SZ",
  "the gambia": "GM",
  "saint helena": "SH",
  // Americas
  méxico: "MX",
  mexique: "MX",
  mexiko: "MX",
  brasil: "BR",
  brésil: "BR",
  brasilien: "BR",
  perú: "PE",
  "república dominicana": "DO",
  ayiti: "HT",
  trinidad: "TT",
  tobago: "TT",
  "the bahamas": "BS",
  barbuda: "AG",
  "saint kitts": "KN",
  nevis: "KN",
  "saint vincent": "VC",
  "turks and caicos": "TC",
  bvi: "VG",
  usvi: "VI",
  cayman: "KY",
  caymans: "KY",
  "sint maarten": "SX",
  "saint maarten": "SX",
  "saint barth": "BL",
  "saint barts": "BL",
  "saint barths": "BL",
  bonaire: "BQ",
  curacao: "CW",
  "saint pierre": "PM",
  falklands: "FK",
  malvinas: "FK",
  "islas malvinas": "FK",
  "south georgia": "GS",
  "kalaallit nunaat": "GL",
  grønland: "GL",
  føroyar: "FO",
  // Oceania
  aotearoa: "NZ",
  "nueva zelanda": "NZ",
  neuseeland: "NZ",
  "down under": "AU",
  australien: "AU",
  "new guinea": "PG",
  "federated states of micronesia": "FM",
  "cocos islands": "CC",
  "keeling islands": "CC",
};

/** Well-known cities by name. The full per-country table is places.ts CITY_TO_COUNTRY. */
export const MAJOR_CITIES: Record<string, string> = {
  "new york": "US",
  "los angeles": "US",
  chicago: "US",
  toronto: "CA",
  "mexico city": "MX",
  "são paulo": "BR",
  "rio de janeiro": "BR",
  "buenos aires": "AR",
  bogotá: "CO",
  lima: "PE",
  london: "GB",
  paris: "FR",
  berlin: "DE",
  madrid: "ES",
  rome: "IT",
  amsterdam: "NL",
  stockholm: "SE",
  warsaw: "PL",
  kyiv: "UA",
  moscow: "RU",
  lagos: "NG",
  nairobi: "KE",
  cairo: "EG",
  johannesburg: "ZA",
  accra: "GH",
  casablanca: "MA",
  mumbai: "IN",
  delhi: "IN",
  bengaluru: "IN",
  jabalpur: "IN",
  tokyo: "JP",
  osaka: "JP",
  seoul: "KR",
  beijing: "CN",
  shanghai: "CN",
  jakarta: "ID",
  manila: "PH",
  bangkok: "TH",
  karachi: "PK",
  dhaka: "BD",
  dubai: "AE",
  tehran: "IR",
  sydney: "AU",
  melbourne: "AU",
  auckland: "NZ",
};

export function buildCountryIndex(): CountryIndex {
  const names = new Map<string, string>();
  for (const [iso2, name] of Object.entries(COUNTRY_NAMES)) {
    names.set(foldText(name), iso2);
  }
  for (const [alias, iso2] of Object.entries(COUNTRY_ALIASES)) {
    names.set(foldText(alias), iso2);
  }
  for (const [place, iso2] of Object.entries(SUBDIVISION_NAMES)) {
    const key = foldText(place);
    if (!names.has(key)) names.set(key, iso2);
  }
  // The matcher resolves these from context; the value is the plain-name reading.
  for (const [place, meaning] of Object.entries(AMBIGUOUS_PLACES)) {
    names.set(foldText(place), meaning.alone ?? meaning.countries[0]!);
  }

  const iso3 = new Map<string, string>();
  for (const [code, iso2] of Object.entries(COUNTRY_ISO3)) {
    iso3.set(foldText(code), iso2);
  }

  const cities = new Map<string, string>();
  for (const [city, iso2] of Object.entries(MAJOR_CITIES)) {
    cities.set(foldText(city), iso2);
  }
  for (const [city, iso2] of Object.entries(CITY_TO_COUNTRY)) {
    const key = foldText(city);
    if (!cities.has(key)) cities.set(key, iso2);
  }

  return { names, iso3, cities };
}

let cached: CountryIndex | undefined;

export function defaultCountryIndex(): CountryIndex {
  cached ??= buildCountryIndex();
  return cached;
}
