import { foldText } from "./normalize.ts";
import type { CountryIndex } from "./types.ts";

export const COUNTRY_NAMES: Record<string, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Bonaire, Sint Eustatius and Saba",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Côte d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin (French part)",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé and Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten (Dutch part)",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Türkiye",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const COUNTRY_ISO3: Record<string, string> = {
  and: "AD",
  are: "AE",
  afg: "AF",
  atg: "AG",
  aia: "AI",
  alb: "AL",
  arm: "AM",
  ago: "AO",
  ata: "AQ",
  arg: "AR",
  asm: "AS",
  aut: "AT",
  aus: "AU",
  abw: "AW",
  ala: "AX",
  aze: "AZ",
  bih: "BA",
  brb: "BB",
  bgd: "BD",
  bel: "BE",
  bfa: "BF",
  bgr: "BG",
  bhr: "BH",
  bdi: "BI",
  ben: "BJ",
  blm: "BL",
  bmu: "BM",
  brn: "BN",
  bol: "BO",
  bes: "BQ",
  bra: "BR",
  bhs: "BS",
  btn: "BT",
  bvt: "BV",
  bwa: "BW",
  blr: "BY",
  blz: "BZ",
  can: "CA",
  cck: "CC",
  cod: "CD",
  caf: "CF",
  cog: "CG",
  che: "CH",
  civ: "CI",
  cok: "CK",
  chl: "CL",
  cmr: "CM",
  chn: "CN",
  col: "CO",
  cri: "CR",
  cub: "CU",
  cpv: "CV",
  cuw: "CW",
  cxr: "CX",
  cyp: "CY",
  cze: "CZ",
  deu: "DE",
  dji: "DJ",
  dnk: "DK",
  dma: "DM",
  dom: "DO",
  dza: "DZ",
  ecu: "EC",
  est: "EE",
  egy: "EG",
  esh: "EH",
  eri: "ER",
  esp: "ES",
  eth: "ET",
  fin: "FI",
  fji: "FJ",
  flk: "FK",
  fsm: "FM",
  fro: "FO",
  fra: "FR",
  gab: "GA",
  gbr: "GB",
  grd: "GD",
  geo: "GE",
  guf: "GF",
  ggy: "GG",
  gha: "GH",
  gib: "GI",
  grl: "GL",
  gmb: "GM",
  gin: "GN",
  glp: "GP",
  gnq: "GQ",
  grc: "GR",
  sgs: "GS",
  gtm: "GT",
  gum: "GU",
  gnb: "GW",
  guy: "GY",
  hkg: "HK",
  hmd: "HM",
  hnd: "HN",
  hrv: "HR",
  hti: "HT",
  hun: "HU",
  idn: "ID",
  irl: "IE",
  isr: "IL",
  imn: "IM",
  ind: "IN",
  iot: "IO",
  irq: "IQ",
  irn: "IR",
  isl: "IS",
  ita: "IT",
  jey: "JE",
  jam: "JM",
  jor: "JO",
  jpn: "JP",
  ken: "KE",
  kgz: "KG",
  khm: "KH",
  kir: "KI",
  com: "KM",
  kna: "KN",
  prk: "KP",
  kor: "KR",
  kwt: "KW",
  cym: "KY",
  kaz: "KZ",
  lao: "LA",
  lbn: "LB",
  lca: "LC",
  lie: "LI",
  lka: "LK",
  lbr: "LR",
  lso: "LS",
  ltu: "LT",
  lux: "LU",
  lva: "LV",
  lby: "LY",
  mar: "MA",
  mco: "MC",
  mda: "MD",
  mne: "ME",
  maf: "MF",
  mdg: "MG",
  mhl: "MH",
  mkd: "MK",
  mli: "ML",
  mmr: "MM",
  mng: "MN",
  mac: "MO",
  mnp: "MP",
  mtq: "MQ",
  mrt: "MR",
  msr: "MS",
  mlt: "MT",
  mus: "MU",
  mdv: "MV",
  mwi: "MW",
  mex: "MX",
  mys: "MY",
  moz: "MZ",
  nam: "NA",
  ncl: "NC",
  ner: "NE",
  nfk: "NF",
  nga: "NG",
  nic: "NI",
  nld: "NL",
  nor: "NO",
  npl: "NP",
  nru: "NR",
  niu: "NU",
  nzl: "NZ",
  omn: "OM",
  pan: "PA",
  per: "PE",
  pyf: "PF",
  png: "PG",
  phl: "PH",
  pak: "PK",
  pol: "PL",
  spm: "PM",
  pcn: "PN",
  pri: "PR",
  pse: "PS",
  prt: "PT",
  plw: "PW",
  pry: "PY",
  qat: "QA",
  reu: "RE",
  rou: "RO",
  srb: "RS",
  rus: "RU",
  rwa: "RW",
  sau: "SA",
  slb: "SB",
  syc: "SC",
  sdn: "SD",
  swe: "SE",
  sgp: "SG",
  shn: "SH",
  svn: "SI",
  sjm: "SJ",
  svk: "SK",
  sle: "SL",
  smr: "SM",
  sen: "SN",
  som: "SO",
  sur: "SR",
  ssd: "SS",
  stp: "ST",
  slv: "SV",
  sxm: "SX",
  syr: "SY",
  swz: "SZ",
  tca: "TC",
  tcd: "TD",
  atf: "TF",
  tgo: "TG",
  tha: "TH",
  tjk: "TJ",
  tkl: "TK",
  tls: "TL",
  tkm: "TM",
  tun: "TN",
  ton: "TO",
  tur: "TR",
  tto: "TT",
  tuv: "TV",
  twn: "TW",
  tza: "TZ",
  ukr: "UA",
  uga: "UG",
  umi: "UM",
  usa: "US",
  ury: "UY",
  uzb: "UZ",
  vat: "VA",
  vct: "VC",
  ven: "VE",
  vgb: "VG",
  vir: "VI",
  vnm: "VN",
  vut: "VU",
  wlf: "WF",
  wsm: "WS",
  yem: "YE",
  myt: "YT",
  zaf: "ZA",
  zmb: "ZM",
  zwe: "ZW",
};

export const COUNTRY_ALIASES: Record<string, string> = {
  usa: "US",
  america: "US",
  "united states of america": "US",
  uk: "GB",
  britain: "GB",
  "great britain": "GB",
  england: "GB",
  holland: "NL",
  uae: "AE",
  "u a e": "AE",
  "south korea": "KR",
  "republic of korea": "KR",
  "north korea": "KP",
  russia: "RU",
  "viet nam": "VN",
  "ivory coast": "CI",
  "czech republic": "CZ",
  czechia: "CZ",
  bharat: "IN",
  hindustan: "IN",
  türkiye: "TR",
  turkiye: "TR",
  turkey: "TR",
  "dr congo": "CD",
  drc: "CD",
  "democratic republic of congo": "CD",
  "congo kinshasa": "CD",
  "congo brazzaville": "CG",
  "republic of congo": "CG",
  burma: "MM",
  "cape verde": "CV",
  "east timor": "TL",
  swaziland: "SZ",
  "the bahamas": "BS",
  "the gambia": "GM",
  "vatican city state": "VA",
  "holy see": "VA",
  macau: "MO",
  "federated states of micronesia": "FM",
  "state of palestine": "PS",
  ceylon: "LK",
};

export const MAJOR_CITIES: Record<string, string> = {
  "new york": "US",
  "los angeles": "US",
  chicago: "US",
  toronto: "CA",
  "mexico city": "MX",
  "sao paulo": "BR",
  "s o paulo": "BR",
  "rio de janeiro": "BR",
  "buenos aires": "AR",
  bogota: "CO",
  lima: "PE",
  london: "GB",
  paris: "FR",
  berlin: "DE",
  madrid: "ES",
  rome: "IT",
  amsterdam: "NL",
  stockholm: "SE",
  warsaw: "PL",
  kyiv: "UA",
  moscow: "RU",
  lagos: "NG",
  nairobi: "KE",
  cairo: "EG",
  johannesburg: "ZA",
  accra: "GH",
  casablanca: "MA",
  mumbai: "IN",
  delhi: "IN",
  bengaluru: "IN",
  tokyo: "JP",
  osaka: "JP",
  seoul: "KR",
  beijing: "CN",
  shanghai: "CN",
  jakarta: "ID",
  manila: "PH",
  bangkok: "TH",
  karachi: "PK",
  dhaka: "BD",
  dubai: "AE",
  tehran: "IR",
  sydney: "AU",
  melbourne: "AU",
  auckland: "NZ",
};

export function buildCountryIndex(): CountryIndex {
  const names = new Map<string, string>();
  for (const [iso2, name] of Object.entries(COUNTRY_NAMES)) {
    names.set(foldText(name), iso2);
  }
  for (const [alias, iso2] of Object.entries(COUNTRY_ALIASES)) {
    names.set(foldText(alias), iso2);
  }

  const iso3 = new Map<string, string>();
  for (const [code, iso2] of Object.entries(COUNTRY_ISO3)) {
    iso3.set(foldText(code), iso2);
  }

  const cities = new Map<string, string>();
  for (const [city, iso2] of Object.entries(MAJOR_CITIES)) {
    cities.set(foldText(city), iso2);
  }

  return { names, iso3, cities };
}

let cached: CountryIndex | undefined;

export function defaultCountryIndex(): CountryIndex {
  cached ??= buildCountryIndex();
  return cached;
}
