/** USPS state codes. Several collide with ISO countries (MA Morocco, CA Canada, IN India). */
export const US_STATE_CODES = new Set([
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "DC",
]);

export const CA_PROVINCE_CODES = new Set([
  "AB",
  "BC",
  "MB",
  "NB",
  "NL",
  "NS",
  "NU",
  "ON",
  "PE",
  "QC",
  "SK",
  "YT",
]);

export const AU_STATE_CODES = new Set(["ACT", "NSW", "QLD", "SA", "TAS", "VIC", "WA"]);

/** Full subdivision names. Skip names that are also countries (Georgia). */
export const SUBDIVISION_NAMES: Record<string, string> = {
  alabama: "US",
  alaska: "US",
  arizona: "US",
  arkansas: "US",
  california: "US",
  colorado: "US",
  connecticut: "US",
  delaware: "US",
  florida: "US",
  hawaii: "US",
  idaho: "US",
  illinois: "US",
  indiana: "US",
  iowa: "US",
  kansas: "US",
  kentucky: "US",
  louisiana: "US",
  maine: "US",
  maryland: "US",
  massachusetts: "US",
  michigan: "US",
  minnesota: "US",
  mississippi: "US",
  missouri: "US",
  montana: "US",
  nebraska: "US",
  nevada: "US",
  "new hampshire": "US",
  "new jersey": "US",
  "new mexico": "US",
  "new york": "US",
  "north carolina": "US",
  "north dakota": "US",
  ohio: "US",
  oklahoma: "US",
  oregon: "US",
  pennsylvania: "US",
  "rhode island": "US",
  "south carolina": "US",
  "south dakota": "US",
  tennessee: "US",
  texas: "US",
  utah: "US",
  vermont: "US",
  virginia: "US",
  washington: "US",
  "west virginia": "US",
  wisconsin: "US",
  wyoming: "US",
  "district of columbia": "US",
  ontario: "CA",
  quebec: "CA",
  "british columbia": "CA",
  alberta: "CA",
  manitoba: "CA",
  saskatchewan: "CA",
  "nova scotia": "CA",
  "new brunswick": "CA",
  newfoundland: "CA",
  "newfoundland and labrador": "CA",
  "prince edward island": "CA",
  yukon: "CA",
  nunavut: "CA",
  "northwest territories": "CA",
  "new south wales": "AU",
  victoria: "AU",
  queensland: "AU",
  "western australia": "AU",
  "south australia": "AU",
  tasmania: "AU",
  "northern territory": "AU",
  "australian capital territory": "AU",
  scotland: "GB",
  wales: "GB",
  "northern ireland": "GB",
};

export const CITY_TO_COUNTRY: Record<string, string> = {
  boston: "US",
  houston: "US",
  phoenix: "US",
  philadelphia: "US",
  "san antonio": "US",
  "san diego": "US",
  dallas: "US",
  austin: "US",
  jacksonville: "US",
  "san jose": "US",
  "fort worth": "US",
  columbus: "US",
  charlotte: "US",
  indianapolis: "US",
  seattle: "US",
  denver: "US",
  nashville: "US",
  "washington dc": "US",
  "washington d c": "US",
  detroit: "US",
  portland: "US",
  "las vegas": "US",
  memphis: "US",
  louisville: "US",
  baltimore: "US",
  milwaukee: "US",
  albuquerque: "US",
  tucson: "US",
  fresno: "US",
  sacramento: "US",
  atlanta: "US",
  miami: "US",
  tampa: "US",
  orlando: "US",
  minneapolis: "US",
  cleveland: "US",
  "kansas city": "US",
  "new orleans": "US",
  "salt lake city": "US",
  pittsburgh: "US",
  cincinnati: "US",
  "st louis": "US",
  "saint louis": "US",
  brooklyn: "US",
  manhattan: "US",
  queens: "US",
  bronx: "US",
  "san francisco": "US",
  oakland: "US",
  montreal: "CA",
  vancouver: "CA",
  calgary: "CA",
  ottawa: "CA",
  edmonton: "CA",
  winnipeg: "CA",
  "quebec city": "CA",
  hamilton: "CA",
  kitchener: "CA",
  "victoria bc": "CA",
  halifax: "CA",
  mississauga: "CA",
  brampton: "CA",
  surrey: "CA",
  laval: "CA",
  gatineau: "CA",
  saskatoon: "CA",
  regina: "CA",
  windsor: "CA",
  london: "GB",
  manchester: "GB",
  birmingham: "GB",
  glasgow: "GB",
  liverpool: "GB",
  leeds: "GB",
  edinburgh: "GB",
  bristol: "GB",
  adelaide: "AU",
  brisbane: "AU",
  perth: "AU",
  canberra: "AU",
  "gold coast": "AU",
  rabat: "MA",
  marrakech: "MA",
  marrakesh: "MA",
  tangier: "MA",
  fez: "MA",
  fes: "MA",
  riyadh: "SA",
  jeddah: "SA",
  "cape town": "ZA",
  durban: "ZA",
  "addis ababa": "ET",
  kampala: "UG",
  dar: "TZ",
  "dar es salaam": "TZ",
  tunis: "TN",
  algiers: "DZ",
  "tel aviv": "IL",
  jerusalem: "IL",
  baghdad: "IQ",
  doha: "QA",
  kuwait: "KW",
  "hong kong": "HK",
  taipei: "TW",
  singapore: "SG",
  "kuala lumpur": "MY",
  hanoi: "VN",
  "ho chi minh": "VN",
  "ho chi minh city": "VN",
  bangalore: "IN",
  hyderabad: "IN",
  chennai: "IN",
  kolkata: "IN",
  pune: "IN",
  lahore: "PK",
  islamabad: "PK",
};

export function countryForSubdivisionCode(code: string): string | null {
  if (US_STATE_CODES.has(code)) return "US";
  if (CA_PROVINCE_CODES.has(code)) return "CA";
  if (AU_STATE_CODES.has(code)) return "AU";
  return null;
}
