// Regenerates the Tamis brand masters in brand/ and every brand PNG in
// icons/ and store/. Needs Chrome or Chromium (CHROME_PATH, or a usual
// install path) and network access to Google Fonts for Inter.
//
//   node scripts/render-brand.mjs                  write everything
//   node scripts/render-brand.mjs --check out.png  also write a toolbar check
//                                                  sheet (16/32 px on light
//                                                  and dark) to out.png
//
// brand/icon-16.svg is drawn by hand and only read. Every other file is
// written by this script; change the code in scripts/brand/, not the output.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { decodePng, encodePng } from "./lib/png.mjs";
import { INTER_FONTS, lockupSvg, markSvg, parseWordmark } from "./brand/artwork.mjs";
import { withChrome } from "./brand/chrome.mjs";
import { marquee, privacyScreenshot, promoTile, socialPreview } from "./brand/compositions.mjs";
import { iconGeometry, iconSvg } from "./brand/icon.mjs";
import { descriptorPath, descriptorUnits, fetchInter, wordmarkSvg, wordmarkUnits } from "./brand/wordmark.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const at = (...parts) => join(root, ...parts);
const checkAt = process.argv.indexOf("--check");
const checkPath = checkAt > 0 ? process.argv[checkAt + 1] : null;

// Toolbar sizes use the hand-pixelled 16 grid. Larger icons use the 5-row
// master, pixel-fitted per size; only 128 carries the Chrome Web Store's
// 16 px transparent padding (96 px artwork).
const MASTER_ICONS = [
  { size: 48, margin: 3 },
  { size: 64, margin: 4 },
  { size: 96, margin: 6 },
  { size: 128, margin: 16 },
  { size: 512, margin: 32 },
];

async function write(path, data) {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, data);
  console.log(`  ${relative(root, path).split("\\").join("/")}`);
}

const svgPage = (svg, width, height) =>
  `<!doctype html><style>html,body{margin:0;background:transparent}svg{display:block;width:${width}px;height:${height}px}</style>${svg}`;

console.log("Fetching Inter 500 and 600 from Google Fonts");
const [inter500, inter600] = await Promise.all([fetchInter(500), fetchInter(600)]);
const icon16 = await readFile(at("brand/icon-16.svg"), "utf8");

await withChrome(async (page) => {
  /** Chrome screenshot, re-encoded; `alpha: false` for store images that must be opaque. */
  async function render(html, width, height, { alpha = true, scale = 1, fonts = [] } = {}) {
    await page.load(html, { width, height, scale, fonts });
    const shot = decodePng(await page.screenshot({ width, height }));
    return encodePng(shot, { alpha });
  }
  const renderSvg = (svg, width, height = width, options) => render(svgPage(svg, width, height), width, height, options);

  console.log("Brand masters");
  const wordmark = wordmarkSvg(await wordmarkUnits(page, inter600));
  const wm = parseWordmark(wordmark);
  const descriptor = descriptorPath(await descriptorUnits(page, inter500), 100);
  const lockup = lockupSvg(wm, descriptor, { dark: false });
  const lockupDark = lockupSvg(wm, descriptor, { dark: true });
  const master = iconSvg(iconGeometry(128, 8), {
    comment:
      "Tamis app icon master (128 artboard, 112 px tile). A round sieve drawn as five feed rows; the marigold row is the one you keep. Generated by scripts/render-brand.mjs.",
  });
  await write(at("brand/wordmark.svg"), wordmark);
  await write(at("brand/lockup.svg"), lockup);
  await write(at("brand/lockup-dark.svg"), lockupDark);
  await write(at("brand/icon.svg"), master);
  await write(at("brand/mark.svg"), markSvg());

  console.log("Extension icons");
  const icons = {};
  icons[16] = await renderSvg(icon16, 16);
  icons[32] = await renderSvg(icon16, 32);
  for (const { size, margin } of MASTER_ICONS) {
    const png = await renderSvg(iconSvg(iconGeometry(size, margin), { id: `i${size}` }), size);
    icons[size] = encodePng(clearMargin(decodePng(png), margin));
  }
  for (const [size, png] of Object.entries(icons)) await write(at(`icons/icon${size}.png`), png);

  console.log("Store and social images");
  await write(at("store/cws-icon-128.png"), icons[128]);
  // Edge's logo fills the frame with the tile; the rounded corners stay clear.
  await write(
    at("store/edge-logo-300.png"),
    await renderSvg(iconSvg(iconGeometry(300, 0), { id: "edge", plate: false }), 300),
  );
  const lockupSize = (svg) => /viewBox="0 0 (\d+) (\d+)"/.exec(svg).slice(1).map(Number);
  for (const [name, svg] of [["lockup", lockup], ["lockup-dark", lockupDark]]) {
    const [width, height] = lockupSize(svg);
    const scale = 1280 / width;
    await write(
      at(`store/${name}.png`),
      await render(svgPage(svg, 1280, Math.round(height * scale)), 1280, Math.round(height * scale)),
    );
  }
  for (const [name, composition] of [
    ["promo-440x280", promoTile(wm)],
    ["marquee-1400x560", marquee(wm)],
    ["github-social-1280x640", socialPreview(wm)],
    ["screenshot-5-privacy-1280x800", privacyScreenshot(wm)],
  ]) {
    const { html, width, height } = composition;
    await write(at(`store/${name}.png`), await render(html, width, height, { alpha: false, fonts: INTER_FONTS }));
  }

  if (checkPath) {
    console.log("Toolbar check sheet");
    await writeFile(checkPath, await render(checkSheet(icons), 900, 440, { scale: 2 }));
    console.log(`  ${checkPath}`);
  }
});

/**
 * Makes the transparent margin exact. Skia's anti-aliasing can leave alpha
 * of a few units in the pixel column beside the tile. The soft drop plate
 * may reach 2/112 of the tile below it.
 */
function clearMargin(image, margin) {
  if (margin === 0) return image;
  const { width, height, data } = image;
  const plate = Math.ceil((2 * (width - 2 * margin)) / 112);
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      const inside = x >= margin && x < width - margin && y >= margin && y < height - margin + plate;
      if (!inside) data.fill(0, (y * width + x) * 4, (y * width + x) * 4 + 4);
    }
  }
  return image;
}

/** Icons at 1x in mock toolbars (with and without a badge) on light and dark, plus 6x zooms. */
function checkSheet(icons) {
  const src = (size) => `data:image/png;base64,${icons[size].toString("base64")}`;
  const panel = (bg, fg, toolbar) => `<div class="p" style="background:${bg};color:${fg}">
    <div>${bg} · toolbar ${toolbar}</div>
    <div class="row">${[16, 32, 48, 64, 96, 128].map((s) => `<img src="${src(s)}" width=${s} height=${s}>`).join("")}</div>
    <div class="row">
      <div class="tb" style="background:${toolbar}"><i></i><i></i><span class="slot"><img src="${src(16)}" width=16 height=16><b>12</b></span><i></i></div>
      <div class="tb" style="background:${toolbar}"><span class="slot"><img src="${src(16)}" width=16 height=16></span></div>
      <div class="tb" style="background:${toolbar}"><span class="slot"><img src="${src(16)}" width=16 height=16><b>3</b></span></div>
    </div>
    <div class="row"><img class="px" src="${src(16)}" width=96 height=96><img class="px" src="${src(32)}" width=96 height=96><img class="px" src="${src(48)}" width=144 height=144></div>
  </div>`;
  return `<!doctype html><style>
  body{margin:0;font:11px system-ui,sans-serif;display:grid;grid-template-columns:1fr 1fr}
  .p{padding:14px 16px;display:flex;flex-direction:column;gap:14px;height:412px}
  .row{display:flex;align-items:center;gap:14px}
  .tb{display:flex;align-items:center;gap:10px;padding:6px 10px;border-radius:18px}
  .slot{position:relative;width:16px;height:16px}
  .slot img{display:block}
  b{position:absolute;left:7px;top:7px;font:600 9px/1 system-ui,sans-serif;color:#14201F;background:#FFB638;border-radius:6px;padding:1px 3px}
  i{width:16px;height:16px;border-radius:50%;background:#9aa0a6;opacity:.6}
  img.px{image-rendering:pixelated}
  </style>${panel("#ffffff", "#3c4043", "#f1f3f4")}${panel("#202124", "#bdc1c6", "#35363a")}`;
}
